### ISSUE TITLE
Add NTP Server list

### ISSUE THREAD

**Issue by florian-asche** [pe-pe/ansible_role_openwrt_config_system#1]
Hi,
it would be cool to also have the possibility to add servers for ntp. I already did some work, hope this is enough that you find some time to add it. By the way, deleting and readding is not nice, didnt find a better way.

```
  tasks:
    - name: Delete NTP
      ignore_errors: yes
      uci:
        command: delete
        key: system.ntp.server
        type: timeserver

    - name: Set NTP
      uci:
        command: add_list
        key: system.ntp.server
        type: timeserver
        value: 192.168.178.1

    - name: Set NTP
      uci:
        command: add_list
        key: system.ntp.server
        type: timeserver
        value: 2.openwrt.pool.ntp.org

    - name: Set NTP
      uci:
        command: add_list
        key: system.ntp.server
        type: timeserver
        value: 3.openwrt.pool.ntp.org

    - name: commit changes
      uci:
        command: commit
```

**Comment by pe-pe** [comment]
Hi Florian, thank you for suggestion. I've added option needed and leveraging on native handling of arrays by upper module (so no delete/add is needed). One CI tests are passed, I'll merge it into main.

**Comment by pe-pe** [comment]
README has been updated with variables to be used for defining server list. Below quick reference:

```
openwrt_config_system:
  ntp:
    enabled: 1
    servers: ["0.europe.pool.ntp.org", "1.europe.pool.ntp.org"]
```
